- name: delete existing directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: yes

- name: craete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: present

- name: download and extract code
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ ccomponent }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes

